#Week3 Homework Assignment

import random # random numbers (https://docs.python.org/3.3/library/random.html)

def CatastropheArt2():
    print("   _                        ")
    print("           \`*-.            ")        
    print("            )  _`-.         ")        
    print("           .  : `. .        ")      
    print("           : _   '  \       ")        
    print("           ; *` _.   `*-._  ")       
    print("           `-.-'          `-.")       
    print("             ;       `       `. ")    
    print("             :.       .        \ ")   
    print("             . \  .   :   .-'   .  ") 
    print("             '  `+.;  ;  '      :   ")
    print("             :  '  |    ;       ;-. ")
    print("             ; '   : :`-:     _.`* ;")
    print("   [fish] .*' /  .*' ; .*`- +'  `*' ")
    print("          `*-*   `*-*  `*-*'        ")
    
def CatastropheArt1():
    print(" *                  *")
    print("     __                *")
    print("  ,db'    *     *")
    print(",d8/       *        *    *")
    print(" 888                      ")
    print(" `db\       *     *")
    print("   `o`_                    **")
    print(" *               *   *    _      *")
    print("       *                 / )")
    print("     *    (\__/) *       ( (  *")
    print("   ,-.,-.,)    (.,-.,-.,-.) ).,-.,-.")
    print("  | @|  ={      }= | @|  / / | @|o |")
    print(" _j__j__j_)     `-------/ /__j__j__j_")
    print(" ________(               /___________")
    print("  |  | @| \              || o|O | @|")
    print("  |o |  |,'\       ,   ,'''|  |  |  |  hjw")
    print(" vV\|/vV|`-'\  ,---\   | \Vv\hjwVv\//v")
    print("            _) )    `. \ /")
    print("           (__/       ) )")
    print("                     (_/")

def GameOverArt():
    print("┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼")
    print("███▀▀▀██┼███▀▀▀███┼███▀█▄█▀███┼██▀▀▀")
    print("██┼┼┼┼██┼██┼┼┼┼┼██┼██┼┼┼█┼┼┼██┼██┼┼┼")
    print("██┼┼┼▄▄▄┼██▄▄▄▄▄██┼██┼┼┼▀┼┼┼██┼██▀▀▀")
    print("██┼┼┼┼██┼██┼┼┼┼┼██┼██┼┼┼┼┼┼┼██┼██┼┼┼")
    print("███▄▄▄██┼██┼┼┼┼┼██┼██┼┼┼┼┼┼┼██┼██▄▄▄")
    print("┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼")
    print("███▀▀▀███┼▀███┼┼██▀┼██▀▀▀┼██▀▀▀▀██▄┼")
    print("██┼┼┼┼┼██┼┼┼██┼┼██┼┼██┼┼┼┼██┼┼┼┼┼██┼")
    print("██┼┼┼┼┼██┼┼┼██┼┼██┼┼██▀▀▀┼██▄▄▄▄▄▀▀┼")
    print("██┼┼┼┼┼██┼┼┼██┼┼█▀┼┼██┼┼┼┼██┼┼┼┼┼██┼")
    print("███▄▄▄███┼┼┼─▀█▀┼┼─┼██▄▄▄┼██┼┼┼┼┼██▄")
    print("┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼")

print("Welcome to the Galaxy! State your name")
numbers=["1","2","3","4","5","6"]
diceroll = (random.randint(1,6))
name = input("Please enter your name >")
planet = input ("Please enter your planet >")
print("Hello agent "+ name +" from "+ planet + "!" + " It's been a tough day in the Galaxy today.")
print("Princess Astracordelia of Uranus has lost her pet Cat-astrophe. You have been chosen to help get her back.")
print("You will be showered with the most precious meteors if can do the job. Do you want to help?")
answer1 = input ("Please enter 'yes' or 'no' >")
if (answer1 == "yes"):
    print("That's great! I'm sure with your help we will be able to find her in no time!") 
    print("The space ships are ready choose the one you like - 1)Invisilator, 2)Zeuster ")
else:
    print("Well you don't really have a choice unless you want to be beheaded...")
    print("The space ships are ready for you. Choose the one you like - 1)Invisilator 2)Zeuster")

spaceship = input("Choose 1 or 2 >")
if (spaceship == "1"):
   print("                        `. ___")
   print("                __,' __`.                _..----....____")
   print("    __...--.'``;.   ,.   ;``--..__     .'    ,-._    _.-'")
   print("_..-''-------'   `'   `'   `'     O ``-''._   (,;') _,'")
   print(",'________________                          \`-._`-','")
   print(" `._              ```````````------...___   '-.._'-:")
   print( "  ```--.._      ,.                     ````--...__\-.")
   print(  "          `.--. `-`                       ____    |  |`")
   print(   "          `. `.                       ,'`````.  ;  ;`")
   print(      "          `._`.        __________   `.      \'__/`")
   print(          "        `-:._____/______/___/____`.     \  `")
   print(             "                  |       `._    `.    \"")
   print(                   "           `._________`-.   `.   `.___")
   print(                  "                         SSt  `------'`")
   print("Great choice! With Invisilator you can now be invisible when close to people and eavesdrop on their conversations.")
   
elif (spaceship == "2"):
    print( "                                         _,'/")
    print( "                                    _.-''._:")
    print( "                            ,-:`-.-'    .:.|")
    print( "                           ;-.''       .::.|")
    print( "            _..------.._  / (:.       .:::.|")
    print( "         ,'.   .. . .  .`/  : :.     .::::.|")
    print( "       ,'. .    .  .   ./    \ ::. .::::::.|")
    print( "     ,'. .  .    .   . /      `.,,::::::::.;/")
    print( "    /  .            . /       ,',';_::::::,:_:")
    print( "   / . .  .   .      /      ,',','::`--'':;._;")
    print( "  : .             . /     ,',',':::::::_:'_,'")
    print( "  |..  .   .   .   /    ,',','::::::_:'_,'")
    print( "  |.              /,-. /,',':::::_:'_,'")
    print( "  | ..    .    . /) /-:/,'::::_:',-'")
    print( "  : . .     .   // / ,'):::_:',' ;")
    print( "   \ .   .     // /,' /,-.','  ./")
    print( "    \ . .  `::./,// ,'' ,'   . /")
    print( "     `. .   . `;;;,/_.'' . . ,'")
    print( "      ,`. .   :;;' `:.  .  ,'")
    print( "      /   `-._,'  ..  ` _.-'")
    print( "     (     _,'``------''  SSt")
    print(        "`--'')")
    print("Great choice! With Zeuster you can travel at the speed of light.")
else:
   print ("I'm sorry. I couldn't understand you.")
   print (spaceship = input("Choose 1, or 2>"))


if (spaceship == "1"):
    print("Since you have chosen Invisilator, you will get a chance to eavesdrop on a conversation.")
    print("Roll the dice and see what you get")
    input("press enter >")
    print("You rolled a "+ str(diceroll) +"!")
    if (diceroll < 4 ):
        print("You lost the conversation between the two alien species wasn't helpful. :(")
        GameOverArt()
    else:
        print("You won! You heard the conversation between Dog-ma and Sparrow-head.")
        print("They just said they saw Cat-Astrophe near the bonsai gardens.")
        input("press enter to go to the bonsai gardens>")
        CatastropheArt1()

elif (spaceship == "2"):
      print("Since you have chosen Zeuster, you will get a chance travel accross 6 planets of which one could be the one where Catastrophe is.")
      print("Roll the dice and see what you get")
      input("press enter >")
      print("You rolled a " + str(diceroll) + "!")
      if (diceroll < 4):
        print("You lost the Cat-astrophe is not on any of the planets that you visited. :(")
        GameOverArt()
      else:
        print("You won! You landed on planet Salmonus. ")
        print("You found catastrophe hunting for fish!")
        input("press enter to go to Salmonus>")
        CatastropheArt2()

